// ---------------------------------------------------------------------------
// Demo seed data.
// A founder testing whether performance-marketing teams struggle to retain and
// apply learnings from high volumes of ad creative. Deliberately mixed:
//   - strong support (real spend + workaround + consequence)
//   - low urgency (frequent but no consequence, no spend)
//   - outright contradiction (not a felt problem)
// The point is to show how Groundwork stops a founder cherry-picking the
// encouraging conversations.
// ---------------------------------------------------------------------------

import type {
  Project, Hypothesis, CustomerSegment, Interview, Decision, Insight,
} from '@/types/domain'

export interface SeedBundle {
  projects: Project[]
  hypotheses: Hypothesis[]
  segments: CustomerSegment[]
  interviews: Interview[]
  decisions: Decision[]
  insights: Insight[]
}

const P = 'proj_pyreel'

const projects: Project[] = [
  {
    id: P,
    name: 'Creative Memory',
    problemStatement:
      'Performance marketing teams struggle to retain and apply learnings from high volumes of advertising creative, causing repeated mistakes and wasted ad spend.',
    solutionIdea: 'A shared library that tags every creative with its results and surfaces past learnings when briefing a new one.',
    industry: 'Marketing technology',
    stage: 'Idea / pre-seed',
    decisionToMake: 'Is the pain of losing creative learnings strong enough that a specific team would change how they work or pay to fix it?',
    deadline: '2026-09-30',
    confidence: 'low',
    createdAt: '2026-07-15T09:00:00.000Z',
  },
]

const segments: CustomerSegment[] = [
  {
    id: 'seg_dtc',
    projectId: P,
    name: 'Performance marketers at DTC brands',
    industry: 'Direct-to-consumer e-commerce',
    role: 'Performance / growth marketer',
    companySize: '20–200 employees',
    geography: 'US / UK',
    workflow: 'Briefs and ships dozens of creatives per week across Meta and TikTok; reviews performance in ad manager and a spreadsheet.',
    triggerEvent: 'A previously winning creative fatigues and CAC spikes.',
    existingAlternative: 'A shared Google Sheet of "winners" plus tribal memory.',
    frequency: 'Weekly',
    severity: 4,
    budgetOwnership: 'Influences tool spend; manager approves.',
    accessibility: 4,
    whyCare: 'Directly measured on CAC and ROAS; repeated creative mistakes cost them money and time.',
    whyNotCare: 'May feel their current spreadsheet is "good enough".',
    hypothesisIds: ['hyp_exists', 'hyp_frequent', 'hyp_urgent', 'hyp_budget'],
  },
  {
    id: 'seg_growth',
    projectId: P,
    name: 'Heads of growth at venture-backed startups',
    industry: 'B2C / B2B SaaS',
    role: 'Head of growth',
    companySize: '30–150 employees',
    geography: 'US',
    workflow: 'Oversees a small team or agency running paid; looks at dashboards weekly, rarely at individual creatives.',
    triggerEvent: 'Board asks why blended CAC moved.',
    existingAlternative: 'Agency reporting decks; Notion docs.',
    frequency: 'Monthly',
    severity: 2,
    budgetOwnership: 'Owns the budget.',
    accessibility: 3,
    whyCare: 'Accountable for efficient growth.',
    whyNotCare: 'Too far from the creative itself to feel the specific pain; delegates it.',
    hypothesisIds: ['hyp_exists', 'hyp_budget'],
  },
  {
    id: 'seg_agency',
    projectId: P,
    name: 'Creative strategists at ad agencies',
    industry: 'Advertising / creative agency',
    role: 'Creative strategist',
    companySize: '10–500 employees',
    geography: 'US / EU',
    workflow: 'Produces creative concepts across multiple client accounts; hands off to media buyers.',
    triggerEvent: 'A client churns citing "creative went stale".',
    existingAlternative: 'Per-client folders; institutional memory of senior staff.',
    frequency: 'Weekly',
    severity: 3,
    budgetOwnership: 'No budget authority; recommends tools.',
    accessibility: 3,
    whyCare: 'Reputation depends on fresh, effective creative.',
    whyNotCare: 'Learnings are client-specific and confidential; hard to pool.',
    hypothesisIds: ['hyp_exists', 'hyp_frequent'],
  },
  {
    id: 'seg_founder',
    projectId: P,
    name: 'Founders running their own paid acquisition',
    industry: 'Early-stage startups',
    role: 'Founder / CEO',
    companySize: '1–15 employees',
    geography: 'Global',
    workflow: 'Runs ads themselves between everything else; little structure.',
    triggerEvent: 'Runway pressure forces a hard look at ad efficiency.',
    existingAlternative: 'Memory; the odd screenshot.',
    frequency: 'Sporadic',
    severity: 2,
    budgetOwnership: 'Owns everything but budget is tiny.',
    accessibility: 5,
    whyCare: 'Every dollar matters at their stage.',
    whyNotCare: 'Volume of creative is too low for the problem to bite; bigger fires elsewhere.',
    hypothesisIds: ['hyp_exists'],
  },
]

const hypotheses: Hypothesis[] = [
  {
    id: 'hyp_exists',
    projectId: P,
    title: 'The learning-loss problem is real',
    type: 'problem_exists',
    belief:
      'We believe performance marketers at DTC brands lose the learnings from past creative when briefing new ones, causing them to repeat creative approaches that already failed. We will treat this as supported when we observe at least 4 of 7 relevant participants describe a specific past repeat-mistake.',
    segmentIds: ['seg_dtc', 'seg_growth', 'seg_agency', 'seg_founder'],
    assumptions: ['Teams ship enough creative for memory to matter', 'Learnings are not already captured elsewhere'],
    evidenceRequired: 'A concrete story of repeating a creative mistake because the learning was lost.',
    disconfirming: 'Participants remember their learnings fine, or ship too little creative for it to matter.',
    supportThreshold: 4,
    confidence: 'medium',
    status: 'testing',
    strength: 'mixed',
    createdAt: '2026-07-16T09:00:00.000Z',
  },
  {
    id: 'hyp_frequent',
    projectId: P,
    title: 'It happens often enough to matter',
    type: 'problem_frequent',
    belief:
      'We believe DTC performance marketers face this at least weekly because of the volume of creative they ship. Supported when 4+ describe it recurring weekly.',
    segmentIds: ['seg_dtc', 'seg_agency'],
    assumptions: ['Creative volume is high and sustained'],
    evidenceRequired: 'Frequency described as weekly or higher, tied to real cadence.',
    disconfirming: 'It comes up only occasionally, or only during rare campaign launches.',
    supportThreshold: 4,
    confidence: 'medium',
    status: 'testing',
    strength: 'strong',
    createdAt: '2026-07-16T09:05:00.000Z',
  },
  {
    id: 'hyp_urgent',
    projectId: P,
    title: 'The consequence is severe enough to act on',
    type: 'problem_urgent',
    belief:
      'We believe the wasted spend and repeated mistakes are painful enough that teams would change their workflow. Supported when 4+ name a real, sizeable consequence.',
    segmentIds: ['seg_dtc'],
    assumptions: ['Wasted spend is attributable and visible'],
    evidenceRequired: 'A quantified or clearly felt consequence of the lost learning.',
    disconfirming: 'Teams shrug it off; the cost is invisible or absorbed.',
    supportThreshold: 4,
    confidence: 'low',
    status: 'testing',
    strength: 'weak',
    createdAt: '2026-07-16T09:10:00.000Z',
  },
  {
    id: 'hyp_budget',
    projectId: P,
    title: 'They have budget and will spend on it',
    type: 'has_budget',
    belief:
      'We believe DTC growth teams already spend on creative-ops tooling and would pay for this. Supported when 3+ show existing spend on adjacent tools.',
    segmentIds: ['seg_dtc', 'seg_growth'],
    assumptions: ['This sits in an existing budget line'],
    evidenceRequired: 'Existing spend on creative analytics / ops tools.',
    disconfirming: 'No budget line; solved with free spreadsheets they are happy with.',
    supportThreshold: 3,
    confidence: 'low',
    status: 'testing',
    strength: 'mixed',
    createdAt: '2026-07-16T09:15:00.000Z',
  },
]

// --- Interviews: deliberately mixed --------------------------------------
const interviews: Interview[] = [
  {
    id: 'int_1',
    projectId: P,
    participantName: 'Maya R.',
    company: 'Loop Supplements (DTC)',
    role: 'Senior Performance Marketer',
    segmentId: 'seg_dtc',
    date: '2026-07-20',
    interviewer: 'You',
    hypothesisIds: ['hyp_exists', 'hyp_frequent', 'hyp_urgent', 'hyp_budget'],
    rawNotes:
      'Last month we relaunched a testimonial angle that we had already killed in Q1 because it tanked. Nobody remembered. We wasted about $6,000 before someone found the old screenshot. This happens basically every week now because we ship 30–40 creatives a week across Meta and TikTok. We keep a shared Google Sheet of winners but it is always out of date and nobody trusts it. We currently pay for Motion for reporting, about $400 a month, and Foreplay for a swipe file. The hardest part is when a new hire briefs a concept we already learned was a dud. What triggered me to care was our CAC spiking after a fatigued creative. Happy to set up a call with our head of growth if it helps.',
    transcript:
      'You: Tell me about the last time a learning got lost.\nMaya: Last month we relaunched a testimonial angle we had already killed in Q1. Nobody remembered it tanked.\nYou: What did that cost you?\nMaya: About six grand in spend before someone dug up the old screenshot.\nYou: How often does something like that happen?\nMaya: Honestly, most weeks. We ship thirty to forty creatives a week.\nYou: What are you using to keep track today?\nMaya: A shared Google Sheet of winners, but it is always stale and nobody trusts it. We pay for Motion and Foreplay too.',
    keyQuotes: ['We wasted about $6,000 before someone found the old screenshot.', 'This happens basically every week.'],
    currentWorkflow: 'Shared Google Sheet of winners; Motion for reporting; Foreplay swipe file.',
    triggerEvents: 'CAC spiking after a fatigued creative.',
    painPoints: 'Repeating a killed angle; sheet always stale and untrusted.',
    consequences: '~$6,000 wasted on a re-run dud.',
    existingTools: 'Motion ($400/mo), Foreplay, Google Sheets.',
    existingSpend: '~$400/mo Motion + Foreplay.',
    workarounds: 'Shared winners sheet, screenshots.',
    frequency: 'Weekly (30–40 creatives/week).',
    severity: 'High',
    decisionProcess: 'Head of growth approves tools.',
    commitments: 'Offered intro to head of growth.',
    followUps: 'Talk to head of growth; see the winners sheet.',
    createdAt: '2026-07-20T15:00:00.000Z',
  },
  {
    id: 'int_2',
    projectId: P,
    participantName: 'Devin K.',
    company: 'NorthPeak (DTC apparel)',
    role: 'Growth Marketer',
    segmentId: 'seg_dtc',
    date: '2026-07-22',
    interviewer: 'You',
    hypothesisIds: ['hyp_exists', 'hyp_frequent', 'hyp_urgent'],
    rawNotes:
      'Yeah it happens weekly, we ship a lot of creative. But honestly it is not really a big deal, we just move on to the next test. I could not tell you a time it actually cost us money in a way I noticed. We do not track that. We use a spreadsheet and it is fine as is. I would not say it is a top three problem for me right now, ad account structure is a bigger headache.',
    keyQuotes: ['It happens weekly but it is not really a big deal.', 'The spreadsheet is fine as is.'],
    currentWorkflow: 'Spreadsheet of tests, moves on quickly.',
    triggerEvents: 'None strong.',
    painPoints: 'Mild; deprioritised.',
    consequences: 'None he could name.',
    existingTools: 'Spreadsheet.',
    existingSpend: 'None specific to this.',
    workarounds: 'Spreadsheet.',
    frequency: 'Weekly.',
    severity: 'Low',
    decisionProcess: 'n/a',
    commitments: 'None.',
    followUps: 'Low priority — note as low-urgency signal.',
    createdAt: '2026-07-22T15:00:00.000Z',
  },
  {
    id: 'int_3',
    projectId: P,
    participantName: 'Priya S.',
    company: 'Halo Studio (agency)',
    role: 'Creative Strategist',
    segmentId: 'seg_agency',
    date: '2026-07-24',
    interviewer: 'You',
    hypothesisIds: ['hyp_exists', 'hyp_frequent'],
    rawNotes:
      'It happens all the time across clients. Last week a junior pitched a concept we had already burned for a similar brand. We built an internal Airtable to log learnings but it is per client and confidential so we cannot really pool them. What breaks is when senior staff who hold the memory are on leave. We have not spent money on a dedicated tool, we just built the Airtable ourselves. It is a real annoyance but every agency lives with it.',
    keyQuotes: ['A junior pitched a concept we had already burned for a similar brand.', 'We built an internal Airtable to log learnings.'],
    currentWorkflow: 'Per-client Airtable; senior staff memory.',
    triggerEvents: 'Junior repeating a burned concept.',
    painPoints: 'Memory walks out the door on leave; learnings siloed per client.',
    consequences: 'Wasted concepting time; occasional client friction.',
    existingTools: 'Airtable (self-built).',
    existingSpend: 'None dedicated.',
    workarounds: 'Airtable, senior memory.',
    frequency: 'Weekly / all the time.',
    severity: 'Medium',
    decisionProcess: 'No budget authority; recommends.',
    commitments: 'None concrete.',
    followUps: 'Who built the Airtable? How often updated? Why kept using it?',
    createdAt: '2026-07-24T15:00:00.000Z',
  },
  {
    id: 'int_4',
    projectId: P,
    participantName: 'Tom B.',
    company: 'Fernwood (seed startup)',
    role: 'Founder',
    segmentId: 'seg_founder',
    date: '2026-07-26',
    interviewer: 'You',
    hypothesisIds: ['hyp_exists'],
    rawNotes:
      'I run our ads myself. Honestly I only make a handful of creatives a month so I remember them fine. This is a cool idea and I think bigger teams would love it, but for me it is not a problem. I have never had this happen in a way that hurt. My real issue is just finding time to make creative at all.',
    keyQuotes: ['I only make a handful of creatives a month so I remember them fine.', 'This is a cool idea but for me it is not a problem.'],
    currentWorkflow: 'Memory; occasional screenshot.',
    triggerEvents: 'None.',
    painPoints: 'Not felt at his volume.',
    consequences: 'None.',
    existingTools: 'None.',
    existingSpend: 'None.',
    workarounds: 'Memory.',
    frequency: 'Rare.',
    severity: 'None',
    decisionProcess: 'Solo.',
    commitments: 'None.',
    followUps: 'Likely wrong segment — low creative volume.',
    createdAt: '2026-07-26T15:00:00.000Z',
  },
  {
    id: 'int_5',
    projectId: P,
    participantName: 'Alina M.',
    company: 'BrightCart (DTC home goods)',
    role: 'Performance Lead',
    segmentId: 'seg_dtc',
    date: '2026-07-29',
    interviewer: 'You',
    hypothesisIds: ['hyp_exists', 'hyp_frequent', 'hyp_urgent', 'hyp_budget'],
    rawNotes:
      'We ship 50+ creatives a week and yes we absolutely repeat mistakes. Two weeks ago we scaled a hook that we had already found fatigues fast, and CAC jumped 30% for three days before we caught it. We currently pay for Motion and we tried building a Notion database of learnings but it died because nobody updated it. What triggered me to act last time was the daily CAC report. The hardest part is onboarding new buyers who have zero context. I would set up a pilot if you had something. Let me introduce you to two other performance leads I know.',
    transcript:
      'You: Walk me through the last repeat.\nAlina: Two weeks ago we scaled a hook we already knew fatigues fast. CAC jumped thirty percent for three days.\nYou: How did you catch it?\nAlina: The daily CAC report. By then we had burned budget.\nYou: What have you tried to prevent it?\nAlina: A Notion database of learnings. It died, nobody updated it. We pay for Motion though.\nYou: What would make this worth solving properly?\nAlina: If it lived where we brief, not a separate doc. I would pilot something. I can intro you to two other leads.',
    keyQuotes: ['CAC jumped 30% for three days before we caught it.', 'A Notion database of learnings died because nobody updated it.'],
    currentWorkflow: 'Motion + a dead Notion database; daily CAC report.',
    triggerEvents: 'Daily CAC report showing a spike.',
    painPoints: 'Repeating fatigued hooks; onboarding buyers with no context.',
    consequences: 'CAC +30% for three days on a known-bad hook.',
    existingTools: 'Motion; Notion (abandoned).',
    existingSpend: 'Motion subscription.',
    workarounds: 'Notion database (failed), tribal memory.',
    frequency: '50+ creatives/week.',
    severity: 'High',
    decisionProcess: 'She leads; can pilot.',
    commitments: 'Would run a pilot; offered two intros.',
    followUps: 'Set up pilot scope; take the two intros.',
    createdAt: '2026-07-29T15:00:00.000Z',
  },
  {
    id: 'int_6',
    projectId: P,
    participantName: 'Jordan P.',
    company: 'Vela (Series A SaaS)',
    role: 'Head of Growth',
    segmentId: 'seg_growth',
    date: '2026-08-01',
    interviewer: 'You',
    hypothesisIds: ['hyp_exists', 'hyp_budget'],
    rawNotes:
      'I own the budget but I am pretty removed from individual creatives, my team and an agency handle that. I could see the value but I personally do not feel the pain day to day. We spend on an agency retainer and some tooling. If my team said they needed it I would probably look at it. I think it sounds useful but I could not point to a specific time it burned us that I know of.',
    keyQuotes: ['I own the budget but I am pretty removed from individual creatives.', 'I think it sounds useful but I could not point to a specific time.'],
    currentWorkflow: 'Delegates to team and agency; looks at dashboards.',
    triggerEvents: 'Board questions on CAC.',
    painPoints: 'Not felt personally.',
    consequences: 'None he could name directly.',
    existingTools: 'Agency retainer, some tooling.',
    existingSpend: 'Agency + tools (owns budget).',
    workarounds: 'Agency decks.',
    frequency: 'Monthly review cadence.',
    severity: 'Low personally',
    decisionProcess: 'Owns budget, defers to team need.',
    commitments: 'Vague — would look if team asked.',
    followUps: 'Buyer but not user — need to reach his team.',
    createdAt: '2026-08-01T15:00:00.000Z',
  },
]

const decisions: Decision[] = [
  {
    id: 'dec_frequent',
    projectId: P,
    hypothesisId: 'hyp_frequent',
    decision: 'proceed_to_solution',
    evidenceBasis: 'Five of six participants who ship real creative volume described this recurring weekly, tied to a concrete cadence (30–50+ creatives/week). Frequency is well supported.',
    remainingUncertainty: 'Frequency is not the same as urgency — being common does not mean it is worth paying to fix.',
    nextTest: 'Shift focus to the urgency hypothesis with the high-volume DTC segment.',
    wouldChangeMind: 'If new high-volume interviews reported this happening only occasionally.',
    createdAt: '2026-08-02T15:00:00.000Z',
  },
]

const insights: Insight[] = [
  {
    id: 'ins_1',
    projectId: P,
    level: 'project',
    title: 'Pain concentrates at high creative volume',
    body: 'Everyone who ships 30+ creatives a week feels this; the founder running a handful a month and the removed head of growth do not. The real segment may be "high-volume DTC performance leads", not "performance marketers" broadly.',
    createdAt: '2026-08-02T16:00:00.000Z',
  },
  {
    id: 'ins_2',
    projectId: P,
    level: 'hypothesis',
    refId: 'hyp_urgent',
    title: 'Frequency is proven, urgency is not',
    body: 'The problem is clearly frequent, but only two participants named a real quantified consequence ($6k; CAC +30%). Do not let the strong frequency signal masquerade as urgency.',
    createdAt: '2026-08-02T16:05:00.000Z',
  },
]

export const seedBundle: SeedBundle = { projects, hypotheses, segments, interviews, decisions, insights }
